# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41efc848ef1bc63e4705794da23afb7c288c1c862d60cfd70c4beb5321897322fd632dcf63fe032461df63dcac0e8950c23c0d16075ffc298203d5fc2999c568

test:
  secret_key_base: b04f359937168f8dd418ca753c5e98c92970a5e5e3824f8bb21e80fb28218182dcf15c9ccd31731c7226a8329f00f2ee0022593c33a7e6b069200e965ba9a3df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
